//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EuroMillion
{
    using System;
    using System.Collections.Generic;
    
    public partial class DateSortie
    {
        public int Id { get; set; }
        public System.DateTime DateSortie1 { get; set; }
        public int NumeroId { get; set; }
    
        public virtual Numero Numero { get; set; }
    }
}
