//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EuroMillion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Numero
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Numero()
        {
            this.DateSortie = new HashSet<DateSortie>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Valeur { get; set; }
        public Nullable<bool> IsEtoile { get; set; }
        public Nullable<double> PourcentageChanceDeSortie { get; set; }
        public Nullable<double> EcartDateSortie { get; set; }
        public Nullable<int> NbrFoisSortie { get; set; }
        public Nullable<int> NbrDeSemaine { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DateSortie> DateSortie { get; set; }
    }
}
